[project]
name = "minimind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.1.0",
    "modelscope>=1.30.0",
    "scikit-learn>=1.7.2",
    "torch>=2.8.0",
    "transformers>=4.56.1",
]
